import {
  apricot,
  avacado,
  banana,
  bringal,
  cauliflower,
  garlic,
  greenChilli,
  lemon,
  papaya,
  pineapple,
  potato,
  pomegranate,
} from "../assets/images/index";

export const products = [
  {
    name: "Potato",
    id: 1,
    price: 30,
    available: 1,
    vendor: "Himachal Pvt Ltd",
    category: "Vegetables",
    image: potato,
    quantity: 1,
  },

  {
    name: "Banana",
    id: 2,
    price: 50,
    available: 1,
    category: "Fruits",
    vendor: "Organic farms",
    image: banana,
    quantity: 1,
  },

  {
    name: "Lemon",
    id: 3,
    price: 20,
    available: 0,
    category: "Vegetables",
    vendor: "Mallikarjuna farms",
    image: lemon,
    quantity: 1,
  },
  {
    name: "Apricot",
    id: 4,
    price: 25,
    available: 1,
    vendor: "Nagpur farms",
    category: "Fruits",
    image: apricot,
    quantity: 1,
  },
  {
    name: "Avacado",
    id: 5,
    price: 25,
    available: 1,
    vendor: "Nagpur farms",
    category: "Fruits",
    image: avacado,
    quantity: 1,
  },
  {
    name: "Bringal",
    id: 6,
    price: 25,
    available: 1,
    vendor: "Mallikarjun farms",
    category: "Vegetables",
    image: bringal,
    quantity: 1,
  },
  {
    name: "Papaya",
    id: 7,
    price: 25,
    available: 1,
    vendor: "Himachal Pvt Ltd",
    category: "Fruits",
    image: papaya,
    quantity: 1,
  },
  {
    name: "Cauliflower",
    id: 8,
    price: 25,
    available: 1,
    vendor: "Mallikarjun farms",
    category: "Vegetables",
    image: cauliflower,
    quantity: 1,
  },
  {
    name: "Pineapple",
    id: 9,
    price: 25,
    available: 1,
    vendor: "Organic farms",
    category: "Fruits",
    image: pineapple,
    quantity: 1,
  },
  {
    name: "Garlic",
    id: 10,
    price: 25,
    available: 1,
    vendor: "Nagpur farms",
    category: "Vegetables",
    image: garlic,
    quantity: 1,
  },
  {
    name: "Pomegranate",
    id: 11,
    price: 25,
    available: 1,
    vendor: "Himachal Pvt Ltd",
    category: "Fruits",
    image: pomegranate,
    quantity: 1,
  },
  {
    name: "Green chilli",
    id: 12,
    price: 25,
    available: 1,
    vendor: "Mallikarjun farms",
    category: "Vegetables",
    image: greenChilli,
    quantity: 1,
  },
];
